/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 02-Oct-2024 12:17:44
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 51;
const int16_T B[51] = {
      -30,    -89,    -81,    120,    447,    569,    251,   -215,   -252,
      200,    455,     11,   -554,   -292,    572,    680,   -403,  -1122,
      -34,   1566,    897,  -1946,  -2697,   2202,  10159,  14092,  10159,
     2202,  -2697,  -1946,    897,   1566,    -34,  -1122,   -403,    680,
      572,   -292,   -554,     11,    455,    200,   -252,   -215,    251,
      569,    447,    120,    -81,    -89,    -30
};
